server:
  port: 8080

spring:
  jwt:
    secret: spring-security-jwt-redis-toy-project
    token-expire-time: 1800
    refresh-token-expire-time: 259200

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: jwt
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: true

  redis:
    host: localhost
    port: 6379
